# Generated by Django 3.0.7 on 2020-12-27 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('real_estate', '0002_auto_20201227_1202'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ufeedback',
            name='description',
        ),
    ]
