# Generated by Django 3.0.7 on 2020-12-27 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('real_estate', '0004_ufeedback_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertyimage',
            name='images',
            field=models.FileField(blank=True, null=True, upload_to='images/'),
        ),
    ]
