# Generated by Django 3.0.7 on 2020-12-27 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('real_estate', '0006_auto_20201227_1528'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='a_address',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='agent',
            name='a_company_address',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='agent',
            name='a_company_email',
            field=models.EmailField(default='', max_length=254),
        ),
        migrations.AddField(
            model_name='agent',
            name='a_company_mobile',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='agent',
            name='a_company_name',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='agent',
            name='a_mobile',
            field=models.CharField(default='', max_length=10),
        ),
    ]
