# Generated by Django 3.0.7 on 2020-12-27 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('real_estate', '0007_auto_20201227_1550'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='a_image',
            field=models.FileField(blank=True, null=True, upload_to='images/'),
        ),
    ]
