# Generated by Django 3.0.7 on 2020-12-28 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('real_estate', '0009_auto_20201227_1814'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='a_image',
            field=models.FileField(blank=True, default='', null=True, upload_to='images/'),
        ),
    ]
