# Generated by Django 3.0.7 on 2020-12-28 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('real_estate', '0012_auto_20201228_2200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='a_image',
            field=models.FileField(default=' ', upload_to='media'),
        ),
    ]
