# Generated by Django 3.0.7 on 2020-12-28 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('real_estate', '0013_auto_20201228_2204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='a_image',
            field=models.FileField(default='', null=True, upload_to='images/', verbose_name=''),
        ),
    ]
