# Generated by Django 3.0.7 on 2021-04-06 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('real_estate', '0017_auto_20210404_1259'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='a_dis',
            field=models.CharField(default='', max_length=500),
        ),
    ]
